name: fspm-utilities
channels:
  - openalea3
  - conda-forge
dependencies:
  - python
  - pandas
  - numpy
  - salib
  - openalea.mtg
  - xarray
  - pyvista
  - matplotlib
  - pint
  - trimesh
  - openalea.plantgl
  - scipy
