name: fspm-utilities
channels:
  - openalea3
  - conda-forge
dependencies:
  - python
  - pandas
  - numpy
  - salib
  - openpyxl
  - openalea.mtg
  - xarray
  - dask
  - pyvista
  - imageio
  - matplotlib
  - brokenaxes
  - pint
  - trimesh
  - openalea.plantgl
  - scipy
